apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{project_name}}
  namespace: <NAMESPACE>
spec:
  replicas: 1
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{project_name}}
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 60 }
        - setWeight: 50
        - pause: { }
  selector:
    matchLabels:
      app: {{project_name}}
